/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package firealarmclient;

import com.sun.xml.internal.ws.policy.sourcemodel.ModelNode;
import firealarmrmi.RMI;
import java.awt.event.WindowEvent;
import java.awt.event.WindowStateListener;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.ArrayList;
import java.util.TimerTask;
import javafx.scene.Parent;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import netscape.javascript.JSObject;

/**
 *
 * @author Dave
 */
public class AdminPage extends javax.swing.JFrame {
    String roomNo;
        String floorNo;
        String status;
        String name;
        UserPage usp = new UserPage();
        
    /**
     * Creates new form AdminPage
     */
        
        Object [] columns = {"sensor id","sensor name","floor no","room no","co2 level","smoke level","status"};
        Object [] insertdata = new Object[7];
        DefaultTableModel model = new DefaultTableModel();
        
        
        
    public AdminPage() {
        initComponents();
        model.setColumnIdentifiers(columns);
        sensorTable.setModel(model);
    }

    public void LoadSensorData()
    {
        
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        floorLabel = new javax.swing.JLabel();
        roomLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sensorTable = new javax.swing.JTable();
        statusTextField = new javax.swing.JTextField();
        sensorNameTextField = new javax.swing.JTextField();
        floorTextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        roomTextField = new javax.swing.JTextField();
        floorLabel1 = new javax.swing.JLabel();
        LogOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        statusLabel.setText("Status");

        floorLabel.setText("Floor no");

        roomLabel.setText("Room no");

        sensorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "sensor id", "sensor name", "floor no", "room no", "co2 level", "smoke level", "status"
            }
        ));
        sensorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sensorTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sensorTable);

        statusTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextFieldActionPerformed(evt);
            }
        });

        floorTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorTextFieldActionPerformed(evt);
            }
        });

        AddButton.setText("Add");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Delete");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Admin Page");

        floorLabel1.setText("Sensor Name");

        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LogOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(floorLabel)
                                    .addComponent(statusLabel)
                                    .addComponent(floorLabel1)
                                    .addComponent(roomLabel))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sensorNameTextField)
                                    .addComponent(floorTextField)
                                    .addComponent(statusTextField)
                                    .addComponent(roomTextField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpdateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sensorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floorLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(floorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(floorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roomLabel))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton)
                            .addComponent(UpdateButton)
                            .addComponent(DeleteButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LogOutButton)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextFieldActionPerformed

    private void floorTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorTextFieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed

        roomNo = roomTextField.getText();
         floorNo = floorTextField.getText();
         status = statusTextField.getText();
         name = sensorNameTextField.getText();
   
         insertdata[0] = "5eb2b32155434f35c897e935";
         insertdata[1] = name;
         insertdata[2] = floorNo;
         insertdata[3] = roomNo;
         insertdata[4] = "00";
         insertdata[5] = "00";
         insertdata[6] = status;
         
         model.addRow(insertdata);
         
         ((DefaultTableModel)sensorTable.getModel()).removeRow(sensorTable.getSelectedRow());
         
         JOptionPane.showMessageDialog(null, "Successfully Updated");
        
        statusTextField.setText("");
        sensorNameTextField.setText("");
        floorTextField.setText("");
        roomTextField.setText("");
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        
        
        
         ArrayList sensorList = new ArrayList<>();
        
         roomNo = roomTextField.getText();
         floorNo = floorTextField.getText();
         status = statusTextField.getText();
         name = sensorNameTextField.getText();
   
         insertdata[0] = "5eb2b32155434f35c897e935";
         insertdata[1] = name;
         insertdata[2] = floorNo;
         insertdata[3] = roomNo;
         insertdata[4] = "00";
         insertdata[5] = "00";
         insertdata[6] = status;
         
         model.addRow(insertdata);
         
         JOptionPane.showMessageDialog(null, "Successfully Added");
         
         statusTextField.setText("");
        sensorNameTextField.setText("");
        floorTextField.setText("");
        roomTextField.setText("");
              
         
         //var obj = {roomNo, floorNo, status};
         sensorDitails sdetails = new sensorDitails();
         sdetails.setFloorNu(floorNo);
         sdetails.setRoomNu(roomNo);
         sdetails.setStatus(status);
         
         sensorList.add(sdetails);
          
         try{
            Registry reg = LocateRegistry.getRegistry("127.0.0.1",8080);
            RMI rmi = (RMI) reg.lookup("server");
            System.out.println("Connected to Server");
            System.out.println("roomNo: " +roomNo + "floorNo: "+floorNo+ "status: " +status);
           // rmi.addData(roomNo, floorNo, status);
            
            //System.out.println(sensorData);
           
            
        }catch(Exception e){
            System.out.println("Error");
            System.out.println(e);
        }
        //addData(String rmNo, String flNo, String stat); 
    }//GEN-LAST:event_AddButtonActionPerformed

    private void sensorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sensorTableMouseClicked
        int rowcount = sensorTable.getRowCount();
        int row = sensorTable.getSelectedRow();
        
        String id = sensorTable.getModel().getValueAt(row, 0).toString();
        String name = sensorTable.getModel().getValueAt(row, 1).toString();
        String florno =  sensorTable.getModel().getValueAt(row, 2).toString();
        String roomno = sensorTable.getModel().getValueAt(row, 3).toString();
        String co2lv = sensorTable.getModel().getValueAt(row, 4).toString();
        String smokelevel = sensorTable.getModel().getValueAt(row, 5).toString();
        String stat = sensorTable.getModel().getValueAt(row, 6).toString();
        
        statusTextField.setText(stat);
        sensorNameTextField.setText(name);
        floorTextField.setText(florno);
        roomTextField.setText(roomno);
        
        
    }//GEN-LAST:event_sensorTableMouseClicked

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed

        ((DefaultTableModel)sensorTable.getModel()).removeRow(sensorTable.getSelectedRow());
        
        JOptionPane.showMessageDialog(null, "Successfully Deleted");
        
        statusTextField.setText("");
        sensorNameTextField.setText("");
        floorTextField.setText("");
        roomTextField.setText("");
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed

        usp.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_LogOutButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
            
           
        });
        
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel floorLabel;
    private javax.swing.JLabel floorLabel1;
    private javax.swing.JTextField floorTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel roomLabel;
    private javax.swing.JTextField roomTextField;
    private javax.swing.JTextField sensorNameTextField;
    private javax.swing.JTable sensorTable;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration//GEN-END:variables
}
